// import image1 from './assets/images/dev.jpg'
// import image2 from './assets/images/dev.jpg'
// import image3 from './assets/images/dev.jpg'
// import image4 from './assets/images/dev.jpg'
// import image5 from './assets/images/dev.jpg'